#!/usr/bin/env python

# Written by Mattias Runge 2008-05-18

import os
import sys
import getopt

def createFile(moduleName, templateFileName, moduleFileName):
	print "Creating " + moduleName + "/" + templateFileName + "..."
	template_file = open("template/" + templateFileName, 'r')
	lines = template_file.readlines()
	template_file.close()

	module_file = open(moduleName + "/" + moduleFileName, 'w')
	
	for line in lines:
		line = line.replace("<template>", moduleName)
		line = line.replace("<TEMPLATE>", moduleName.upper())

		module_file.write(line)

	module_file.close()

def main():
	if len(sys.argv) <= 1:
		print "Syntax: ./CreateModule <module name>"
		sys.exit()
	
	moduleName = sys.argv[1]

	if os.path.exists(moduleName):
		print "A module named " + moduleName + " already exists."
		sys.exit()

	print "Creating " + moduleName + " directory..."
	os.mkdir("./" + moduleName + "/")

	createFile(moduleName, "config.inc.template", "config.inc.template")
	createFile(moduleName, "protocol.h", "protocol.h")
	createFile(moduleName, "sources.list", "sources.list")
	createFile(moduleName, "template.h", moduleName + ".h")
	createFile(moduleName, "template.c", moduleName + ".c")

if __name__ == "__main__":
	main()
