/* This file is automatically generated. Do not edit. */

#ifndef CONFIG_H_
#define CONFIG_H_

#define HW_NAME CoreCard
#define HW_VERSION 1
#define AUTOSTART 5
#define NODE_HW_ID 0x1d1a6fa1
#define NODE_ID 0x62UL
#define F_CPU 8000000UL
#define MCU atmega168
#define HIGHFUSE 0xdc
#define LOWFUSE 0xe2
#define EXTFUSE 0x02
#define BOOT_START 0x3c00
#define CAN_CONTROLLER MCP2515
#define MCP_CS_PORT PORTC
#define MCP_CS_DDR DDRC
#define MCP_CS_BIT PC3
#define MCP_CAN_BITRATE_KBPS 250
#define MCP_CLOCK_FREQ_MHZ 20
#define MCP_CLOCK_PRESC 1

#endif /*CONFIG_H_*/
