MAKECANIDSCRIPT = ../PcSoftware/scripts/makeCanId/makeCanId.pl
XMLFILE = data.xml
MODULEIDFILE = ../EmbeddedSoftware/AVR/avr-lib/drivers/can/moduleid.h

all:
	$(MAKECANIDSCRIPT) -x $(XMLFILE) -c $(MODULEIDFILE)
